### PR TITLE
Robots.txt

### PR DESCRIPTION
**Pull request by Bookmonkey**

### CODE REVIEW

**Comment by NikxDa** [comment]
Is there a way to make all *.baa.nz domains unindexed by default? Maybe with Search Console? I am not familiar with this, but if there's an easier way than the "per-site" variant, that'd be neat

**Comment by Bookmonkey** [comment]
We have added *.baa.nz property to the Search console :) 

But I am not super convinced this is the best route to take with this issue. As Google is still indexing tas.baa.nz. The Search console says "Indexed, though blocked by robots.txt". Ive updated the robots.txt file to allow and left the noindex tag in to see if it will remove itself from the index.

I think the only way to avoid it is to just have the noindex meta tag on our Page.ss file. The internet doesnt have a definitive answer on this.

**Comment by ethanjohnstone** [comment]
@Bookmonkey Do we still want this to be merged in though?

**Comment by Bookmonkey** [comment]
I dont see why not? It still prevents robots from crawling the assets and admin

**Pull request merged**
